// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		//getting inouts
		int count = Integer.parseInt(args[0]);

		//generating numbers and sorting them
		int lowCount = 0;
		int highCount = 0;
		
		for (int i = 0; i < count; i++) { 
			double random = Math.random();
			if (random > 0.5) {
				highCount++;
			} else {
				lowCount++;
			}
		}

		//printing output and checking ratio
		System.out.println("> 0.5: " + highCount);
		System.out.println("<= 0.5: " + lowCount);
		if (lowCount == 0) {
			System.out.println("no numbers below 0.5");
		} else {
			if (highCount == 0) {
			System.out.println("no numbers above or equal 0.5");
			} else {
				double ratio = (double) Math.min(lowCount,highCount) / Math.max(lowCount, highCount);
				System.out.println("Ratio: " + ratio);
			}
		}
		


	}
}
